Document: pyoa
Title: Debian pyoa Manual
Author: <insert document author here>
Abstract: This manual describes what pyoa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyoa/pyoa.sgml.gz

Format: postscript
Files: /usr/share/doc/pyoa/pyoa.ps.gz

Format: text
Files: /usr/share/doc/pyoa/pyoa.text.gz

Format: HTML
Index: /usr/share/doc/pyoa/html/index.html
Files: /usr/share/doc/pyoa/html/*.html
