#*******************************************************************
#   Copyright 2002-2008  LSI Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#*******************************************************************
#
#--------------------------------------------------------------------
# Read the OA based XML files generated by Doxygen (v 1.2.15).
# Use these files to generate class and function descriptions for
# the Python/OpenAccess interface.
#--------------------------------------------------------------------
#

import pyXml2DoxData

import os
import os.path
import sys
import string
import pprint

# ===================================================================
# Read all the xml files in the doxygen output directory.
# Skip those files associated with the C++ Interface Module.
def Process():
    indir="DoxExt/xml"
    outdir="DoxData"
    files=[]
    skip=['classobj',
          'classT',
          'classU',
          'classV',
          ]
    for name in os.listdir(indir):
        parts=string.split(name,'.')
        if (len(parts)!=2): continue
        if (parts[1]!='xml'): continue
        name=parts[0]
        if (name[0:2]!='oa' and name[0:7]!='classoa'): continue
        if (name in skip): continue
        files.append(name)
    print "Files:"
    pprint.pprint(files)
    
    pyXml2DoxData.ProcessFiles(files,indir,outdir)

# ===================================================================
if (__name__=="__main__"):
    Process()
    
